# Generated by Django 4.2.2 on 2024-12-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='unknown_file', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
