# Generated by Django 4.2.2 on 2024-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_file_category_file_file_name_file_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
