# Generated by Django 4.2.2 on 2024-12-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_alter_file_file_name_alter_file_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
